### PR TITLE
Fix selection, update about page footer to match index

### PR DESCRIPTION
**Pull request by HideakiAtsuyo**
:flushed:

- About
=> Added Sticky Footer on about page
=> Removed the possitiliby to select text*

- Index
=> Removed the possitiliby to select text*

\* = This way is probably not the best since we can use an handler for it but probably an update will be made later for it :)

And beautified a bit

:flushed:

### CODE REVIEW

**Comment by HideakiAtsuyo** [comment]
And also moved the checkbox above the buttons (looks better) and added a new line because if you not have it in full screen it's in a new line and in full screen it's just next to the buttons :(

**Comment by dr4k0nia** [comment]
I think selecting text should be available for the code element in case people want to manually copy it or only parts. With the other changes I can agree ^^

**Comment by HideakiAtsuyo** [comment]
> I think selecting text should be available for the code element in case people want to manually copy it or only parts. With the other changes I can agree ^^

Solved :)

**Comment by HideakiAtsuyo** [comment]
In case you want it to be selectable EVEN before just go [Here](https://github.com/dr4k0nia/simple-string-encryption/blob/711a0f375d937a7243be4c6eaf24acd2289e288a/index.html#L128) and remove the "notSelectable" class :)

**Pull request merged**
